apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  app: "{{ .Values.app.name }}-netpol"
spec:
  podSelector:
    matchLabels:
      app: "{{ .Values.app.name }}"
  policyTypes:
  - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: "{{ .Values.app.frontendappname }}"
      ports:
        - protocol: TCP
          port: {{ .Values.service.externalPort }}