pool:
  vmImage: 'ubuntu-latest'

variables:
  registryServerName: '<<ecr endpoint id>>.ecr.us-east-1.amazonaws.com'
  imageName: 'teststudyfrontendapi'

steps:
- bash: docker build -f $(system.defaultWorkingDirectory)/teststudy-frontend/Dockerfile -t $(registryServerName)/$(imageName):$(build.buildId)
  displayName: 'docker build for teststudy-frontend'
  continueOnError: false

- bash: docker push $(registryServerName)/$(imageName):$(build.buildId)
  displayName: 'ECR docker push'

- task: HelmInstaller@1
  displayName: 'Install Helm'
  inputs:
    helmVersionToInstall: <helm-version>

- bash: helm package --version $(build.buildId) --destination $(build.artifactStagingDirectory) $(system.defaultWorkingDirectory)/teststudy-frontend/charts/teststudyfrontend
  displayName: 'helm package creation'

- bash: |
    helm registry login --username AWS --password-stdin ***************
    helm push $(build.artifactStagingDirectory)/teststudyfrontend-$(build.buildId).tgz
  displayName: 'ECR helm push'