# Default values for myChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: "mybackendappimage"
  imagePullPolicy: Never
environment:
  name: local

app:
  name: teststudyapibackend
  frontendappname: teststudyapifrontend

container:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 512Mi

mongodburl:  "http://mongodbapp-service:27017"

service:
  internalPort: 8080
  externalPort: 8080

