apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}-service"
  labels:
    app: "{{ .Values.app.name }}"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
  selector:
     app: "{{ .Values.app.name }}"
