apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  labels:
    environment: {{.Values.environment}}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.basedomain }}
    secretName: keyvault-certificate
  rules:
  - host: {{ .Values.ingress.basedomain }}
    http:
      paths:
      - backend:
          service:
            name: {{ template "fullname" . }}
            port: 
              number: 8080
        path: /api
        pathType: Exact
