apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Values.app.name }}"
  labels:
    app: "{{ .Values.app.name }}"
spec:
  replicas: 1
  serviceName: "{{ .Values.app.name }}-service"  
  selector:
    matchLabels: 
      app: "{{ .Values.app.name }}"
  template:
    metadata:
      labels: 
        app: "{{ .Values.app.name }}"      
    spec:    
      securityContext: 
        runAsUser: 1000
      terminationGracePeriodSeconds: {{ .Values.mongodb.terminationGracePeriodSeconds }}
      containers:
        - name: mongodb
          image: "mongo:latest"
          imagePullPolicy: Always
          env:          
            - name: MONGODB_PORT_NUMBER
              value: "{{ .Values.mongodb.port }}"   
          volumeMounts:
            - name: datadir
              mountPath: "{{ .Values.mongodb.mountPath }}" 
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: "{{ .Values.app.name }}-pvc"