kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.app.name }}-pvc"
  labels:
     app: "{{ .Values.app.name }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi