apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}-service"
  labels:
    app: "{{ .Values.app.name }}"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.mongodb.port }}
      targetPort: http
      protocol: TCP
  selector:
    app: "{{ .Values.app.name }}"
