# Default values for myChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: "<ecr-repo-url>"

ingress:
  basedomain: app.teststudy.com

environment:
  name: staging

app:
  name: teststudyapifrontend

container:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 512Mi

backendserviceurl: "http://teststudyapibackend-service.default.svc.cluster.local"

certificate: ""
key: ""

service:
  internalPort: 9000
  externalPort: 9000